[project]
name = "shap-docs-ko"
version = "0.1.0"
description = "SHAP documentation in Korean"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
quarto = ">=1.4"
python = "3.11"
jupyter = "*"

[tasks]
render = "quarto render mybook"
